#!/usr/bin/env node
/*
 * Authority index generator.
 *
 * Scans this repository's data/ directories and writes index/index-{type}.json
 * files consumed by BA.authority.
 *
 * No npm dependencies. Records are machine-generated by the editors, so a
 * lightweight regex/string scan is sufficient (no DOM in bare Node).
 *
 * Usage:  node tools/build-index.js [repoRoot] [--base <uri>]
 *   repoRoot  defaults to the script's ../ (the repo root).
 *   --base    overrides the record-URI base (keep in sync with BA.config.baseUri).
 */

"use strict";

var fs = require("fs");
var path = require("path");

var DEFAULT_BASE = "https://biblia-arabica.com";

// type -> { dir (relative to repo root), path (entity path segment) }
var TYPES = [
  { type: "manuscript", dir: "data/manuscripts", pathSeg: "manuscript" },
  { type: "person", dir: "data/persons", pathSeg: "person" },
  { type: "place", dir: "data/places", pathSeg: "place" },
  { type: "work", dir: "data/works", pathSeg: "work" }
];

// ---------- CLI ----------

function parseArgs(argv) {
  var out = { repoRoot: null, base: DEFAULT_BASE };
  for (var i = 0; i < argv.length; i++) {
    if (argv[i] === "--base") { out.base = argv[++i]; }
    else if (out.repoRoot === null) { out.repoRoot = argv[i]; }
  }
  if (!out.repoRoot) out.repoRoot = path.join(__dirname, "..");
  // strip a trailing slash from the base so joins are clean
  out.base = out.base.replace(/\/+$/, "");
  return out;
}

// ---------- tiny XML scanning ----------

function decodeEntities(s) {
  return s
    .replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, function (_, n) { return String.fromCharCode(parseInt(n, 10)); })
    .replace(/&amp;/g, "&");
}

// Return [{ attrs, inner }] for every <tag ...>…</tag> or self-closing <tag .../>.
function elements(xml, tag) {
  var out = [];
  var re = new RegExp("<" + tag + "\\b([^>]*?)(?:/>|>([\\s\\S]*?)</" + tag + ">)", "g");
  var m;
  while ((m = re.exec(xml)) !== null) {
    out.push({ attrs: m[1] || "", inner: m[2] === undefined ? "" : m[2] });
  }
  return out;
}

function attrVal(attrs, name) {
  var m = attrs.match(new RegExp("(?:^|\\s)" + name + "\\s*=\\s*\"([^\"]*)\""));
  return m ? m[1] : "";
}

// Plain text of an element inner: strip tags, decode entities, collapse space.
function textOf(inner) {
  return decodeEntities(String(inner).replace(/<[^>]*>/g, "")).replace(/\s+/g, " ").trim();
}

function dedupe(list) {
  var seen = {}, out = [];
  list.forEach(function (v) { if (v && !seen[v]) { seen[v] = true; out.push(v); } });
  return out;
}

// Restrict extraction to the record body so the fixed teiHeader (which also
// contains <title> elements) never leaks into headwords/altNames.
function bodyOf(xml) {
  var i = xml.indexOf("<text");
  return i === -1 ? xml : xml.slice(i);
}

// ---------- per-type extraction ----------

// Returns { headword, altNames }.
function extract(type, xml, file) {
  var body = bodyOf(xml);
  var headword = "";
  var altNames = [];

  if (type === "person") {
    // altNames: the person's other name forms (persName) + associated places
    // (placeName in birth/death/floruit/residence).
    var names = elements(body, "persName").map(function (p) {
      var nm = elements(p.inner, "name")[0];
      return { type: attrVal(p.attrs, "type"), text: nm ? textOf(nm.inner) : textOf(p.inner) };
    }).filter(function (n) { return n.text; });
    var hw = names.filter(function (n) { return n.type === "ba-headword"; })[0];
    headword = hw ? hw.text : "";
    var pPlaces = elements(body, "placeName").map(function (pl) { return textOf(pl.inner); });
    altNames = dedupe(names.map(function (n) { return n.text; }).concat(pPlaces)
      .filter(function (t) { return t && t !== headword; }));

  } else if (type === "place") {
    // altNames: the place's other name forms (placeName) only.
    var pns = elements(body, "placeName").map(function (p) {
      return { type: attrVal(p.attrs, "type"), text: textOf(p.inner) };
    }).filter(function (n) { return n.text; });
    var phw = pns.filter(function (n) { return n.type === "ba-headword"; })[0];
    headword = phw ? phw.text : "";
    altNames = dedupe(pns.map(function (n) { return n.text; }).filter(function (t) { return t !== headword; }));

  } else if (type === "work") {
    // The work's own title/author/persName are direct children of the root
    // <bibl xml:id="work-…">. Strip nested (bibliography) <bibl> blocks so their
    // <title>s don't leak into altNames.
    var wRoot = /<bibl\b[^>]*\bxml:id="work[^"]*"[^>]*>([\s\S]*)<\/bibl>/.exec(body);
    var wInner = wRoot ? wRoot[1] : body;
    var wPrev;
    do { wPrev = wInner; wInner = wInner.replace(/<bibl\b[^>]*>[\s\S]*?<\/bibl>/g, ""); } while (wInner !== wPrev);
    var titles = elements(wInner, "title").map(function (t) {
      return { type: attrVal(t.attrs, "type"), text: textOf(t.inner) };
    }).filter(function (t) { return t.text; });
    var thw = titles.filter(function (t) { return t.type === "ba-headword"; })[0];
    headword = thw ? thw.text : "";
    var wExtra = titles.map(function (t) { return t.text; })
      .concat(elements(wInner, "author").map(function (a) { return textOf(a.inner); }))
      .concat(elements(wInner, "persName").map(function (p) { return textOf(p.inner); }));
    altNames = dedupe(wExtra.filter(function (t) { return t && t !== headword; }));

  } else if (type === "manuscript") {
    var msName = textOf((elements(body, "msName")[0] || { inner: "" }).inner);
    if (msName) {
      headword = msName;
    } else {
      var repo = textOf((elements(body, "repository")[0] || { inner: "" }).inner);
      var idno = textOf((elements(body, "idno")[0] || { inner: "" }).inner);
      headword = [repo, idno].filter(Boolean).join(" ").trim();
    }
    // altNames: authors + mentioned texts (titles) from msContents only.
    var mcMatch = /<msContents\b[^>]*>([\s\S]*?)<\/msContents>/.exec(body);
    var mcInner = mcMatch ? mcMatch[1] : "";
    var msExtra = elements(mcInner, "author").map(function (a) { return textOf(a.inner); })
      .concat(elements(mcInner, "title").map(function (t) { return textOf(t.inner); }));
    altNames = dedupe(msExtra.filter(function (t) { return t && t !== headword; }));
  }

  if (!headword) {
    console.warn("  ! no extractable headword in " + file + " — using placeholder");
    headword = "[no headword] " + file;
    return { headword: headword, altNames: altNames, extracted: false };
  }
  return { headword: headword, altNames: altNames, extracted: true };
}

// ---------- main ----------

function buildType(repoRoot, base, spec) {
  var absDir = path.join(repoRoot, spec.dir);
  if (!fs.existsSync(absDir)) {
    console.warn("Skipping missing directory: " + spec.dir);
    return null;
  }
  var files = fs.readdirSync(absDir);
  var records = [];
  var recordFiles = 0; // files matching \d+\.xml (the only ones that count as records)
  var extracted = 0;   // of those, how many yielded a real (non-placeholder) headword

  files.forEach(function (name) {
    var full = path.join(absDir, name);
    if (!fs.statSync(full).isFile()) return;
    var m = name.match(/^(\d+)\.xml$/);
    if (!m) {
      if (/\.xml$/i.test(name) || name.indexOf(".") !== -1) {
        console.warn("Skipping non-numeric file: " + spec.dir + "/" + name);
      }
      return;
    }
    recordFiles++;
    var id = m[1];
    var xml = fs.readFileSync(full, "utf8");
    var ex = extract(spec.type, xml, spec.dir + "/" + name);
    if (ex.extracted) extracted++;
    records.push({
      id: id,
      uri: base + "/" + spec.pathSeg + "/" + id,
      headword: ex.headword,
      altNames: ex.altNames,
      file: spec.dir + "/" + id + ".xml"
    });
  });

  records.sort(function (a, b) { return parseInt(a.id, 10) - parseInt(b.id, 10); });

  return { spec: spec, records: records, recordFiles: recordFiles, extracted: extracted };
}

function main() {
  var args = parseArgs(process.argv.slice(2));
  var repoRoot = path.resolve(args.repoRoot);
  var indexDir = path.join(repoRoot, "index");
  if (!fs.existsSync(indexDir)) fs.mkdirSync(indexDir, { recursive: true });

  var generated = new Date().toISOString();
  var fatal = false;

  TYPES.forEach(function (spec) {
    var res = buildType(repoRoot, args.base, spec);
    if (!res) return; // missing dir already warned
    var payload = { generated: generated, type: spec.type, records: res.records };
    var outPath = path.join(indexDir, "index-" + spec.type + ".json");
    fs.writeFileSync(outPath, JSON.stringify(payload, null, 2) + "\n");
    console.log("Wrote " + path.relative(repoRoot, outPath) + " (" + res.records.length + " record" +
      (res.records.length === 1 ? "" : "s") + ")");
    // Fail only when the directory holds real record files (\d+\.xml) yet none
    // of them yielded an extractable record. Directories whose only contents are
    // .gitkeep or other non-record files are legitimately empty (exit 0).
    if (res.recordFiles > 0 && res.extracted === 0) {
      console.error("ERROR: " + spec.dir + " contains record files but produced zero extractable records.");
      fatal = true;
    }
  });

  if (fatal) process.exit(1);
}

main();
